server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  #    loadbalancer:
  #      zone: default
  zipkin:
    base-url: http://127.0.0.1:9411/zipkin/
  datasource:
    url: jdbc:h2:mem:user
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    hostname: localhost


#DEPARTMENT-SERVICE:
#  ribbon:
#    listOfservers: localhost:8082,localhost:8085,localhost:8086